<div style="display: none;" id='modal-html' class="modal-edit">
    <input type="radio" name="shipping_method" id="shippinng" value="Shipping">Shipping <br>
    <input type="radio" name="shipping_method" id="pickup" value="Pickup">Pickup <br>
    <input type="radio" name="shipping_method" id="dealer_arrange" value="Dealer">Dealer Arrange Shipping <br>
</div>
<div style="display: none;" id='modal-html-active'>
    <p>You have active quote</p>
</div>

<button class="modal-event">New Order</button>
<button class="modal-edit" id="modal-edit">Edit Order</button>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal',
        'mage/storage'
    ], function(
        $,
        modal,
        storage
    ) {
        $(document).ready(function() {
            var deOrder = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                buttons: [{
                    text: $.mage.__('Save & Continue'),
                    class: 'continueBtn',
                    click: function () {
                        var selectedOption = $('input[name="shipping_method"]:checked').val();
                        if (selectedOption) {
                        storage.post(
                            'torder/index/savequote',
                            JSON.stringify({
                                "field":'Ship Type',
                                "value":selectedOption
                            }),
                            true
                        ).done(function(response) {
                            // alert('Success save');
                            $('#modal-html').modal("closeModal");
                        }).fail(function(response) {
                            // alert('save Error occurred.');
                        });
                        } else {
                            alert('Please select an option.');
                        }
                    }
                }]
            };

            var atOrder = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                buttons: [{
                        text: $.mage.__('Delete Quote'),
                        class: 'continueBtn',
                        click: function() {
                            storage.get(
                                'torder/index/deletequote',
                                '',
                                true
                                // return response controller file
                            ).done(function(response) {
                                // alert('success occurred.');
                                $('#modal-html-active').modal("closeModal");
                                $('#modal-html').modal("openModal");
                            }).fail(function(response) {
                                // alert('delete Error occurred.');
                            });
                        }
                    },
                    {
                        text: $.mage.__('Close Popup'),
                        class: 'continueBtn',
                        click: function() {
                            $('#modal-html-active').modal("closeModal");
                        }
                    }
                ]
            };

            var editOrder = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                buttons: [{
                    text: $.mage.__('Confirm'),
                    class: 'editBtn',
                    click: function () {
                        var editOption = $('input[name="shipping_method"]:checked').val();
                        if (editOption) {
                        storage.post(
                            'torder/index/savequote',
                            JSON.stringify({
                                "field":'Ship Type',
                                "value":editOption
                            }),
                            true
                        ).done(function(response) {
                            // alert('Success edit');
                            $('#modal-html').modal("closeModal");
                        }).fail(function(response) {
                            // alert('edit Error occurred.');
                        });
                        } else {
                            alert('Please select an option.');
                        }
                    }
                }]
            };

            $(".modal-event").click(function() {
                storage.get(
                    'torder/index/index',
                    '',
                    true
                    // return response controller file
                ).done(function(response) {
                    if (response.isActive == 0) {
                        $('#modal-html').modal(deOrder).modal("openModal");

                    } else if (response.isActive == 1) {
                        $('#modal-html-active').modal(atOrder).modal("openModal");
                    } else {
                        alert('else occurred.');
                    }
                }).fail(function(response) {
                    alert('main Error occurred.');
                });
            });


            // edit quote
            $("#modal-edit").click(function() {
                storage.get(
                    'torder/index/editquote',
                    '',
                    true
                    // return response controller file
                ).done(function(response) {
                    if (response.editOption !== undefined) {
                        $('input[name="shipping_method"][value="' + response.editOption + '"]').prop('checked', true);
                        $('#modal-html').modal(editOrder).modal("openModal");

                    }
                }).fail(function(response) {
                    // alert('modal-edit Error occurred.');
                });
            });

            if(window.checkoutConfig.shipping_type == null)
            {                       
                $('#modal-html').modal(deOrder).modal("openModal");
            
            }

        });
    });
</script>